server.port=8082
spring.application.name=ms-personajes

# Base de datos propia de ms-personajes
spring.datasource.url=jdbc:mysql://localhost:3306/personajes_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Compatibilidad Spring Cloud
spring.cloud.compatibility-verifier.enabled=false

# URL de ms-razas
ms-razas.url=http://ms-razas
