server:
  port: 8089

spring:
  application:
    name: ms-gremios
  sql:
    init:
      mode: always

  # Base de datos propia de ms-gremios
  datasource:
    url: jdbc:mysql://localhost:3306/gremios_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  # Compatibilidad Spring Cloud y Arranque
  cloud:
    compatibility-verifier:
      enabled: false
  main:
    web-application-type: servlet

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Documentación Swagger / OpenApi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    version: openapi_3_0